apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-esmf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-esmf@sha256:c16931fec541fcccef032e20c40b74d0e1f0417b9a77ebe21b29d2e26ed3686d
        name: my-nodejs
        resources: {}
status: {}
